// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGR5jvc3iQwBbqZMtmdb2AkuHjRlKqDV8',
    appId: '1:278194023228:web:PLACEHOLDER',
    messagingSenderId: '278194023228',
    projectId: 'smart-service-borewll',
    authDomain: 'smart-service-borewll.firebaseapp.com',
    storageBucket: 'smart-service-borewll.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGR5jvc3iQwBbqZMtmdb2AkuHjRlKqDV8',
    appId: '1:278194023228:android:b80960c0d3ab03b3dd4c39',
    messagingSenderId: '278194023228',
    projectId: 'smart-service-borewll',
    storageBucket: 'smart-service-borewll.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZrUJORci8mD5yxp4UE_K3EqWDZXY_s8',
    appId: '1:278194023228:ios:15a745b2f4d88e90dd4c39',
    messagingSenderId: '278194023228',
    projectId: 'smart-service-borewll',
    storageBucket: 'smart-service-borewll.firebasestorage.app',
    iosBundleId: 'com.example.servicemaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApZrUJORci8mD5yxp4UE_K3EqWDZXY_s8',
    appId: '1:278194023228:ios:15a745b2f4d88e90dd4c39',
    messagingSenderId: '278194023228',
    projectId: 'smart-service-borewll',
    storageBucket: 'smart-service-borewll.firebasestorage.app',
    iosBundleId: 'com.example.servicemaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGR5jvc3iQwBbqZMtmdb2AkuHjRlKqDV8',
    appId: '1:278194023228:web:PLACEHOLDER',
    messagingSenderId: '278194023228',
    projectId: 'smart-service-borewll',
    authDomain: 'smart-service-borewll.firebaseapp.com',
    storageBucket: 'smart-service-borewll.firebasestorage.app',
  );
}
